### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by Blake-Haydon**
# Description

Hi, just want to say that this is such a cool project and would really like to contribute!

I have tried to update the main README.md so that it is easier to get up and running however I cannot figure out how to do step 3 and create the environment variables. Any help would be appreciated.

### CODE REVIEW

**Comment by Blake-Haydon** [comment]
Every time I run flask it starts in production mode and I cannot figure out how to start it in local mode.

Screen Shot 2021-09-02 at 6 17 20 pm

**Comment by salgozino** [comment]
Hey @Blake-Haydon thank you for the contribution.
About your questions:
1) To set the enviromental variables you have to create them. There are a few ways to do that:
   * If you are under linux: > export

**Comment by Blake-Haydon** [comment]
Thanks for the help @salgozino! I'll have another go this week and let you know how I do.

**Comment by Blake-Haydon** [comment]
Just got it running locally @salgozino. Thanks for the help!

Screen Shot 2021-09-14 at 9 00 13 pm

The README is updated to reflect the steps I took to get it running

**Comment by salgozino** [comment]
The PR was merged. Thank you for the contribution!

**Pull request merged**
